### ISSUE TITLE
Can't update Lancelot redmi 9

### ISSUE THREAD

**Issue by bennanihaithem23** [SuperiorOS/android-issue#33]
time: 1711621622807
device fp:Redmi/lancelot_global/lancelot:11/RP1A.200720.011/V12.5.6.0.RJCMIXM:user/release-keys
product board:mt6768
superior vers:SuperiorOS-Fourteen-lancelot-GAPPS-RELEASE-20240118-1006
msg: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{7ed8637 19517:org.superioros.updater/u0a338} targetSDK=34
stacktrace: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{7ed8637 19517:org.superioros.updater/u0a338} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6806)
	at android.app.Service.startForeground(Service.java:775)
	at org.superioros.updater.controller.UpdaterService.handleUpdateStatusChange(UpdaterService.java:280)
	at org.superioros.updater.controller.UpdaterService.-$$Nest$mhandleUpdateStatusChange(UpdaterService.java:0)
	at org.superioros.updater.controller.UpdaterService$1.onReceive(UpdaterService.java:116)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:319)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8240)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
New Snippet  Fork 
 Memochō

**Comment by xiaozhao45** [comment]
I'm having the same issue,but no one seems to have responded to this issue...

**Comment by xiaozhao45** [comment]
# Steps to reproduce:
1. Flash the official version of SuperiorOS lower than the latest version for the redmi9
2. Open: Settings - System - Updates - Download Updates

# Expected behavior:
Download the OTA update package from the server and install it

# Actual behavior:
The "Updater" program stops running and goes back to Settings - System.

# Log:
[crash-org-superioros-updater-26_04-19-56-37_900.zip](https://github.com/SuperiorOS/android-issue/files/15130551/crash-org-superioros-updater-26_04-19-56-37_900.zip)

**Comment by Darkstar085** [comment]
Go to recovery and flash manually...
